# Generated by Django 5.0.6 on 2024-08-21 13:25

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

table_name_data = [
    {
        "Name": "Userrole",
        "Type__description": "Setup Table",
        "Group__code": "users",
        "Prefix": "URL",
    },
    {
        "Name": "User",
        "Type__description": "Setup Table",
        "Group__code": "cor",
        "Prefix": "USR",
    },
    {
        "Name": "AccessControl",
        "Type__description": "Setup Table",
        "Group__code": "users",
        "Prefix": "ACP",
    },
    {
        "Name": "RoleAccessControl",
        "Type__description": "Setup Table",
        "Group__code": "users",
        "Prefix": "RAC",
    },
    {
        "Name": "UserAccessControl",
        "Type__description": "Setup Table",
        "Group__code": "users",
        "Prefix": "UAC",
    },
    {
        "Name": "AccessType",
        "Type__description": "Lookup Table",
        "Group__code": "users",
        "Prefix": "AST",
    },
    {
        "Name": "AccessControlType",
        "Type__description": "Lookup Table",
        "Group__code": "users",
        "Prefix": "ACT",
    },
]

table_attributes_data = [
    {
        "table_name__name": "Userrole",
        "attrib_name": "role_name",
        "data_type__description": "String",
        "constraint": False,
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "AccessControl",
        "attrib_name": "access_name",
        "data_type__description": "String",
        "constraint": False,
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "UserName",
        "DATA_TYPE__description": "String",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": False,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "first_name",
        "DATA_TYPE__description": "String",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "last_name",
        "DATA_TYPE__description": "String",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "email",
        "DATA_TYPE__description": "String",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": False,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "is_staff",
        "DATA_TYPE__description": "Boolean",
        "CONSTRAINT": "",
        "DESC": "Only for django admin operation",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "is_superuser",
        "DATA_TYPE__description": "Boolean",
        "CONSTRAINT": "",
        "DESC": "Only for django admin operation",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "is_active",
        "DATA_TYPE__description": "Boolean",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "date_joined",
        "DATA_TYPE__description": "DateTime",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "password",
        "DATA_TYPE__description": "String",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": False,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
    {
        "table_name__name": "User",
        "ATTRIB_NAME": "last_login",
        "DATA_TYPE__description": "DateTime",
        "CONSTRAINT": "",
        "DESC": "",
        "POSITION": "",
        "IS_NULLABLE": True,
        "char_max_length": "",
        "NUMERIC_PRECISION": "",
        "IS_IDENTITY": "",
        "IDENTITY_GENERATION": "",
        "IDENTITY_START": "",
        "IDENTITY_INCREMENT": "",
        "COMMENT": "",
    },
]

table_relations_data = [
    {
        "Relation_Table_1__name": "User",
        "Relation_Column_1__attrib_name": "id",
        "Relation_Table_2__name": "Userrole",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "RoleAccessControl",
        "Relation_Column_1__attrib_name": "access_control",
        "Relation_Table_2__name": "AccessControl",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "RoleAccessControl",
        "Relation_Column_1__attrib_name": "role",
        "Relation_Table_2__name": "Userrole",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "RoleAccessControl",
        "Relation_Column_1__attrib_name": "access_type",
        "Relation_Table_2__name": "AccessType",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "UserAccessControl",
        "Relation_Column_1__attrib_name": "user",
        "Relation_Table_2__name": "User",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "UserAccessControl",
        "Relation_Column_1__attrib_name": "access_control",
        "Relation_Table_2__name": "AccessControl",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "UserAccessControl",
        "Relation_Column_1__attrib_name": "access_type",
        "Relation_Table_2__name": "AccessType",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
    {
        "Relation_Table_1__name": "AccessControl",
        "Relation_Column_1__attrib_name": "access_control_type",
        "Relation_Table_2__name": "AccessControlType",
        "Relation_Column_2__attrib_name": "",
        "Type__description": "Foreign",
        "Attr1": "",
        "Attr2": "",
        "Attr3": "",
        "ui_display": True,
        "reverse_display": True,
    },
]


table_group = [
    {"description": "Users", "Code": "users"},
]

role_data = [
    {"name": "SuperUser", "code": "SU"},
    {"name": "PharmacyUser", "code": "PU"},
]

access_control_type = [
    {"description": "Entity", "code": "ENT"},
    {"description": "Attribute", "code": "ATB"},
    {"description": "Custom", "code": "CTM"},
]

access_type = [
    {"description": "Full", "code": "FULL"},
    {"description": "Read", "code": "READ"},
    {"description": "Encrypt", "code": "ECPT"},
    {"description": "Last3", "code": "L3"},
]


def transform_this_data(data):
    return [{key.lower(): val for key, val in eac_rec.items()} for eac_rec in data]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "users", "AccessControlType", access_control_type)
    migrate_bulk_data(apps, "users", "AccessType", access_type)
    migrate_bulk_data(apps, "users", "Userrole", role_data)
    migrate_bulk_data(apps, "core", "Tablegroup", transform_this_data(table_group))
    migrate_bulk_data(apps, "core", "Tablename", transform_this_data(table_name_data))
    for rel in table_relations_data:
        table_attributes_data.append(
            {
                "table_name__name": rel["Relation_Table_1__name"],
                "ATTRIB_NAME": rel["Relation_Column_1__attrib_name"],
                "data_type__description": "UUID",
                "CONSTRAINT": True,
                "DESC": "",
                "POSITION": 0,
                "IS_NULLABLE": False,
                "char_max_length": "",
                "NUMERIC_PRECISION": "",
                "IS_IDENTITY": "",
                "IDENTITY_GENERATION": "",
                "IDENTITY_START": "",
                "IDENTITY_INCREMENT": "",
                "COMMENT": "",
            }
        )
    migrate_bulk_data(
        apps, "core", "Tableattribute", transform_this_data(table_attributes_data)
    )
    migrate_bulk_data(
        apps, "core", "Tablerelationship", transform_this_data(table_relations_data)
    )


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(
        apps, "core", "Tablerelationship", transform_this_data(table_relations_data)
    )
    reverse_migrated_bulk_data(
        apps, "core", "Tableattribute", transform_this_data(table_attributes_data)
    )
    reverse_migrated_bulk_data(
        apps, "core", "Tablename", transform_this_data(table_name_data)
    )
    reverse_migrated_bulk_data(apps, "users", "Userrole", role_data)
    reverse_migrated_bulk_data(apps, "users", "AccessType", access_type)
    reverse_migrated_bulk_data(apps, "users", "AccessControlType", access_control_type)
    reverse_migrated_bulk_data(
        apps, "core", "Tablegroup", transform_this_data(table_group)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_core_data, reverse_migrated_core_data),
    ]
