# Generated by Django 5.0.6 on 2024-09-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0021_auto_20240917_1841"),
        ("users", "0003_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                db_column="usr_pharmacy",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pharmacy.pharmacy",
            ),
        ),
    ]
