# Generated by Django 5.0.6 on 2024-09-25 11:52

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

role_data = [{"name": "Volume Group", "code": "VG"}]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "users", "Userrole", role_data)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "users", "Userrole", role_data)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_pharmacy"),
    ]

    operations = [migrations.RunPython(migrate_core_data, reverse_migrated_core_data)]
