# Generated by Django 5.0.6 on 2024-09-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0022_fileprocessinglogs_log"),
        ("users", "0005_auto_20240925_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="volume_group",
            field=models.ForeignKey(
                blank=True,
                db_column="usr_volume_group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pharmacy.volumegroup",
            ),
        ),
    ]
