# Generated by Django 5.0.6 on 2024-08-21 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attributetype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "LKP_ATP_AttributeType",
            },
        ),
        migrations.CreateModel(
            name="Keytype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "LKP_KTP_KeyType",
            },
        ),
        migrations.CreateModel(
            name="Tableattribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "attrib_name",
                    models.CharField(db_column="tat_attrib_name", max_length=128),
                ),
                (
                    "constraint",
                    models.CharField(
                        blank=True,
                        db_column="tat_constraint",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("desc", models.TextField(blank=True, db_column="tat_desc", null=True)),
                (
                    "position",
                    models.IntegerField(
                        blank=True, db_column="tat_position", null=True
                    ),
                ),
                (
                    "is_nullable",
                    models.BooleanField(
                        blank=True, db_column="tat_is_nullable", null=True
                    ),
                ),
                (
                    "char_max_length",
                    models.IntegerField(
                        blank=True, db_column="tat_char_max_len", null=True
                    ),
                ),
                (
                    "numeric_precision",
                    models.IntegerField(
                        blank=True, db_column="tat_numeric_precision", null=True
                    ),
                ),
                (
                    "is_identity",
                    models.BooleanField(
                        blank=True, db_column="tat_is_identity", null=True
                    ),
                ),
                (
                    "identity_generation",
                    models.IntegerField(
                        blank=True, db_column="tat_identity_generation", null=True
                    ),
                ),
                (
                    "identity_start",
                    models.IntegerField(
                        blank=True, db_column="tat_identity_start", null=True
                    ),
                ),
                (
                    "identity_increment",
                    models.IntegerField(
                        blank=True, db_column="tat_identity_increment", null=True
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, db_column="tat_comment", max_length=128, null=True
                    ),
                ),
                (
                    "attrib_code",
                    models.CharField(
                        blank=True,
                        db_column="tat_attrib_code",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "default_value",
                    models.BooleanField(
                        blank=True, db_column="tat_default_value", null=True
                    ),
                ),
            ],
            options={
                "db_table": "SET_TAT_TableAttribute",
            },
        ),
        migrations.CreateModel(
            name="Tablegroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "SET_TGP_TableGroup",
            },
        ),
        migrations.CreateModel(
            name="Tablename",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_column="tnm_name", max_length=128)),
                ("prefix", models.CharField(db_column="tnm_prefix", max_length=128)),
            ],
            options={
                "db_table": "SET_TNM_TableName",
            },
        ),
        migrations.CreateModel(
            name="Tablerelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "attr1",
                    models.CharField(
                        blank=True, db_column="trp_attr1", max_length=128, null=True
                    ),
                ),
                (
                    "attr2",
                    models.CharField(
                        blank=True, db_column="trp_attr2", max_length=128, null=True
                    ),
                ),
                (
                    "attr3",
                    models.CharField(
                        blank=True, db_column="trp_attr3", max_length=128, null=True
                    ),
                ),
                (
                    "ui_display",
                    models.BooleanField(
                        blank=True, db_column="trp_ui_display", null=True
                    ),
                ),
                (
                    "reverse_display",
                    models.BooleanField(
                        blank=True, db_column="trp_reverse_display", null=True
                    ),
                ),
            ],
            options={
                "db_table": "SET_TRP_TableRelationship",
            },
        ),
        migrations.CreateModel(
            name="Tabletype",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "LKP_TTP_TableType",
            },
        ),
    ]
