# Generated by Django 5.0.6 on 2024-08-28 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_auto_20240820_1654"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsalesinfo",
            name="original_info",
            field=models.JSONField(db_column="gsi_original_info", default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="affiliation_1_name",
            field=models.CharField(
                blank=True,
                db_column="phm_affiliation_1_name",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="gln",
            field=models.CharField(
                blank=True, db_column="phm_gln", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="principal_email",
            field=models.CharField(
                blank=True, db_column="phm_principal_email", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacysalesinfo",
            name="original_info",
            field=models.JSONField(db_column="psi_original_info", default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volumegroupsalesinfo",
            name="original_info",
            field=models.JSONField(db_column="vgi_original_info", default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antidiabetic_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antidiabeticglp1_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antipsychotic_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="brand_rx_dropship_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="brand_rx_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_rx_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_source_overrides",
            field=models.IntegerField(
                blank=True, db_column="gsi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_source_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="gpo_generic_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="net_generic_source_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="net_source_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="non_rx_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="rx_sales",
            field=models.IntegerField(blank=True, db_column="gsi_rx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_compliance_pct_base_member",
            field=models.IntegerField(
                blank=True, db_column="gsi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_compliance_pct_new_member",
            field=models.IntegerField(
                blank=True, db_column="gsi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_override_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spd_sales",
            field=models.IntegerField(blank=True, db_column="gsi_spd_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_cancer",
            field=models.IntegerField(
                blank=True, db_column="gsi_spx_cancer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_hep_c",
            field=models.IntegerField(blank=True, db_column="gsi_spx_hep_c", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_hiv",
            field=models.IntegerField(blank=True, db_column="gsi_spx_hiv", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_ms",
            field=models.IntegerField(blank=True, db_column="gsi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_ra",
            field=models.IntegerField(blank=True, db_column="gsi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_sales",
            field=models.IntegerField(blank=True, db_column="gsi_spx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="total_sales",
            field=models.IntegerField(
                blank=True, db_column="gsi_total_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="corp_name",
            field=models.CharField(
                blank=True, db_column="phm_corp_name", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="dba",
            field=models.CharField(
                blank=True, db_column="phm_dba", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="dea",
            field=models.CharField(
                blank=True, db_column="phm_dea", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="email",
            field=models.CharField(
                blank=True, db_column="phm_email", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="ncpa",
            field=models.CharField(
                blank=True, db_column="phm_ncpa", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="principal_name",
            field=models.CharField(
                blank=True, db_column="phm_principal_name", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="affiliation_level3_name",
            field=models.CharField(
                blank=True,
                db_column="psi_affiliation_level3 _name",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="dba",
            field=models.CharField(
                blank=True, db_column="psi_dba", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="ship_to_default_delivery_plant",
            field=models.CharField(
                blank=True,
                db_column="psi_ship_to_default_delivery_plant",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="volume_group_name",
            field=models.CharField(
                blank=True, db_column="psi_volume_group_name", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="phone",
            field=models.BigIntegerField(blank=True, db_column="phm_phone", null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="affiliation_2_name",
            field=models.BigIntegerField(
                blank=True, db_column="phm_affiliation_2_name", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="campus_master",
            field=models.BigIntegerField(db_column="phm_campus_master"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="fax",
            field=models.BigIntegerField(blank=True, db_column="phm_fax", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="npi",
            field=models.BigIntegerField(blank=True, db_column="phm_npi", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="principal_cell",
            field=models.BigIntegerField(
                blank=True, db_column="phm_principal_cell", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="sap_ship_to_no",
            field=models.BigIntegerField(db_column="phm_sap_ship_to_no"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="state_license",
            field=models.BigIntegerField(
                blank=True, db_column="phm_state_license", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="volume_group",
            field=models.ForeignKey(
                blank=True,
                db_column="phm_volumegroup_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_volumegroup_id",
                to="pharmacy.volumegroup",
            ),
        ),
        migrations.RemoveField(
            model_name="groupsalesinfo",
            name="reporting_period",
        ),
        migrations.AddField(
            model_name="groupsalesinfo",
            name="reporting_period_end",
            field=models.DateField(
                blank=True, db_column="gsi_reporting_period_end", null=True
            ),
        ),
        migrations.AddField(
            model_name="groupsalesinfo",
            name="reporting_period_start",
            field=models.DateField(
                blank=True, db_column="gsi_reporting_period_start", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="ship_to_customer_name",
            field=models.CharField(
                blank=True, db_column="psi_ship_to_customer_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="affiliation_level3_number",
            field=models.BigIntegerField(
                blank=True, db_column="psi_affiliation_level3_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antidiabetic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antidiabeticglp1_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antipsychotic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="brand_rx_dropship_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="brand_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="campus_number",
            field=models.BigIntegerField(
                blank=True, db_column="psi_campus_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="cust_ship_number",
            field=models.BigIntegerField(
                blank=True, db_column="psi_cust_ship_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="cust_sold_number",
            field=models.BigIntegerField(
                blank=True, db_column="psi_cust_sold_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_source_overrides",
            field=models.BigIntegerField(
                blank=True, db_column="psi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="gpo_generic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="net_generic_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="net_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="non_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_compliance_pct_base_member",
            field=models.BigIntegerField(
                blank=True, db_column="psi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_compliance_pct_new_member",
            field=models.BigIntegerField(
                blank=True, db_column="psi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_override_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spd_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_spd_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_cancer",
            field=models.BigIntegerField(
                blank=True, db_column="psi_spx_cancer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_hep_c",
            field=models.BigIntegerField(
                blank=True, db_column="psi_spx_hep_c", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_hiv",
            field=models.BigIntegerField(
                blank=True, db_column="psi_spx_hiv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_ms",
            field=models.BigIntegerField(blank=True, db_column="psi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_ra",
            field=models.BigIntegerField(blank=True, db_column="psi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_spx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="total_sales",
            field=models.BigIntegerField(
                blank=True, db_column="psi_total_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="volume_group_number",
            field=models.BigIntegerField(
                blank=True, db_column="psi_volume_group_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antidiabetic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antidiabeticglp1_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antipsychotic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="brand_rx_dropship_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="brand_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_source_overrides",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="gpo_generic_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="net_generic_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="net_source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="non_rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="number_of_campus_locations",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_number_of_campus_locations", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="rx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_compliance_pct_base_member",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_compliance_pct_new_member",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_override_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spd_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_spd_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_cancer",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_spx_cancer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_hep_c",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_spx_hep_c", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_hiv",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_spx_hiv", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_ms",
            field=models.BigIntegerField(blank=True, db_column="vgi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_ra",
            field=models.BigIntegerField(blank=True, db_column="vgi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_spx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="total_sales",
            field=models.BigIntegerField(
                blank=True, db_column="vgi_total_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="volume_group_number",
            field=models.BigIntegerField(db_column="vgi_volume_group_number"),
        ),
        migrations.CreateModel(
            name="RebateInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "div",
                    models.IntegerField(blank=True, db_column="rbi_div", null=True),
                ),
                (
                    "sales_rep_name",
                    models.CharField(
                        blank=True,
                        db_column="rbi_sales_rep_name",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "affiliation_level_2",
                    models.BigIntegerField(
                        blank=True, db_column="rbi_affiliation_level_2", null=True
                    ),
                ),
                (
                    "affiliation_level_2_name",
                    models.CharField(
                        blank=True,
                        db_column="rbi_affiliation_level_2_name",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "customer_num",
                    models.BigIntegerField(
                        blank=True, db_column="rbi_customer_num", null=True
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        db_column="rbi_customer_name",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "dba_name",
                    models.CharField(
                        blank=True, db_column="rbi_dba_name", max_length=128, null=True
                    ),
                ),
                (
                    "volume_group",
                    models.BigIntegerField(
                        blank=True, db_column="rbi_volume_group", null=True
                    ),
                ),
                (
                    "payer_customer_number",
                    models.BigIntegerField(
                        blank=True, db_column="rbi_payer_customer_number", null=True
                    ),
                ),
                (
                    "campus_number",
                    models.BigIntegerField(
                        blank=True, db_column="rbi_campus_number", null=True
                    ),
                ),
                (
                    "net_sales",
                    models.IntegerField(
                        blank=True, db_column="rbi_net_sales", null=True
                    ),
                ),
                (
                    "total_rx",
                    models.IntegerField(
                        blank=True, db_column="rbi_total_rx", null=True
                    ),
                ),
                (
                    "brand_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_brand_net", null=True
                    ),
                ),
                (
                    "source_sales",
                    models.IntegerField(
                        blank=True, db_column="rbi_source_sales", null=True
                    ),
                ),
                (
                    "spx_1_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_spx_1_net", null=True
                    ),
                ),
                (
                    "spx_2_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_spx_2_net", null=True
                    ),
                ),
                (
                    "spx_3_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_spx_3_net", null=True
                    ),
                ),
                (
                    "spx_4_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_spx_4_net", null=True
                    ),
                ),
                (
                    "spx_5_net",
                    models.IntegerField(
                        blank=True, db_column="rbi_spx_5_net", null=True
                    ),
                ),
                (
                    "glp_1_anti_diabetics",
                    models.IntegerField(
                        blank=True, db_column="rbi_glp-1_anti-diabetics", null=True
                    ),
                ),
                (
                    "spd_sales",
                    models.IntegerField(
                        blank=True, db_column="rbi_spd_sales", null=True
                    ),
                ),
                (
                    "dropship",
                    models.IntegerField(
                        blank=True, db_column="rbi_dropship", null=True
                    ),
                ),
                (
                    "brand_rebatable",
                    models.IntegerField(
                        blank=True, db_column="rbi_brand_rebatable", null=True
                    ),
                ),
                (
                    "net_rx_after_exclusions",
                    models.IntegerField(
                        blank=True, db_column="rbi_net_rx_after_exclusions", null=True
                    ),
                ),
                (
                    "source_rebatable",
                    models.IntegerField(
                        blank=True, db_column="rbi_source_rebatable", null=True
                    ),
                ),
                (
                    "campus_source_sales",
                    models.IntegerField(
                        blank=True, db_column="rbi_campus_source_sales", null=True
                    ),
                ),
                (
                    "campus_net_rx_after_exclusions",
                    models.IntegerField(
                        blank=True,
                        db_column="rbi_campus_net_rx_after_exclusions",
                        null=True,
                    ),
                ),
                (
                    "generic_compliance",
                    models.IntegerField(
                        blank=True, db_column="rbi_generic_compliance", null=True
                    ),
                ),
                (
                    "campus_compliance_based_on_net_rx_sales_after_exclusions",
                    models.IntegerField(
                        blank=True,
                        db_column="rbi_campus_compliance_based_on_net_rx_sales_after_exclusions",
                        null=True,
                    ),
                ),
                (
                    "volume_group_compliance_based_on_net_rx_sales_after_exclusions",
                    models.IntegerField(
                        blank=True,
                        db_column="rbi_volume_group_compliance_based_on_net_rx_sales_after_exclusions",
                        null=True,
                    ),
                ),
                (
                    "net_sales_per_location",
                    models.IntegerField(
                        blank=True, db_column="rbi_net_sales_per_location", null=True
                    ),
                ),
                (
                    "revised_payment_terms",
                    models.IntegerField(
                        blank=True, db_column="rbi_revised_payment_terms", null=True
                    ),
                ),
                (
                    "payment_terms_rebate_pct",
                    models.IntegerField(
                        blank=True, db_column="rbi_payment_terms_rebate_pct", null=True
                    ),
                ),
                (
                    "payments_terms_rebate_amt",
                    models.IntegerField(
                        blank=True, db_column="rbi_payments_terms_rebate_amt", null=True
                    ),
                ),
                (
                    "monthly_source_rebate_pct_via_campus_compliance",
                    models.IntegerField(
                        blank=True,
                        db_column="rbi_monthly_source_rebate_pct_via_campus_compliance",
                        null=True,
                    ),
                ),
                (
                    "monthly_source",
                    models.IntegerField(
                        blank=True, db_column="rbi_monthly_source", null=True
                    ),
                ),
                (
                    "brand_rebate_pct",
                    models.IntegerField(
                        blank=True, db_column="rbi_brand_rebate_pct", null=True
                    ),
                ),
                (
                    "brand_rebate_amt",
                    models.IntegerField(
                        blank=True, db_column="rbi_brand_rebate_amt", null=True
                    ),
                ),
                (
                    "total_brand_rebate_pct",
                    models.IntegerField(
                        blank=True, db_column="rbi_total_brand_rebate_pct", null=True
                    ),
                ),
                (
                    "total_brand",
                    models.IntegerField(
                        blank=True, db_column="rbi_total_brand", null=True
                    ),
                ),
                ("original_info", models.JSONField(db_column="rbi_original_info")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        db_column="rbi_pharmacy",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebateinfo_pharmacy_pharmacy_id",
                        to="pharmacy.pharmacy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OPT_RBI_RebateInfo",
            },
        ),
        migrations.CreateModel(
            name="LeadFrom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "LKP_LFO_LeadFrom",
            },
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="curr_primary_wholesaler",
            field=models.CharField(
                blank=True,
                db_column="phm_curr_primary_wholesaler",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="curr_total_volume",
            field=models.BigIntegerField(
                blank=True, db_column="phm_curr_total_volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="est_80_committed_amt",
            field=models.BigIntegerField(
                blank=True, db_column="phm_est_80_committed_amt", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="expected_gcr_pct",
            field=models.IntegerField(
                blank=True, db_column="phm_expected_gcr_pct", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="hiv_volume",
            field=models.IntegerField(
                blank=True, db_column="phm_hiv_volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_affiliated_member",
            field=models.BooleanField(
                db_column="phm_is_affiliated_member", default=False
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_startup_pharma",
            field=models.BooleanField(db_column="phm_is_startup_pharma", default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_sub_group_member",
            field=models.BooleanField(
                db_column="phm_is_sub_group_member", default=False
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_un_affiliated_member",
            field=models.BooleanField(
                db_column="phm_is_un_affiliated_member", default=False
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="proposed_payment_terms",
            field=models.CharField(
                blank=True, db_column="phm_proposed_payment_terms", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="sub_group_name",
            field=models.CharField(
                blank=True, db_column="phm_sub_group_name", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="volume_group_num",
            field=models.BigIntegerField(
                blank=True, db_column="phm_volume_group_num", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="lead_from",
            field=models.ForeignKey(
                blank=True,
                db_column="phm_lead_from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharma_lead_from_id",
                to="pharmacy.leadfrom",
            ),
        ),
    ]
