# Generated by Django 5.0.6 on 2024-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pharmacy",
            "0003_groupsalesinfo_original_info_and_more_squashed_0012_leadfrom_pharmacy_curr_primary_wholesaler_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacy",
            name="lead_from",
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="cell",
            field=models.BigIntegerField(blank=True, db_column="phm_cell", null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="contact_name",
            field=models.CharField(
                blank=True, db_column="phm_contact_name", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_cardinal_lead",
            field=models.BooleanField(db_column="phm_is_cardinal_lead", default=False),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_kinray_lead",
            field=models.BooleanField(db_column="phm_is_kinray_lead", default=False),
        ),
        migrations.DeleteModel(
            name="LeadFrom",
        ),
    ]
