# Generated by Django 5.0.6 on 2024-08-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0013_remove_pharmacy_lead_from_pharmacy_cell_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="affiliation_2_name",
            field=models.CharField(
                blank=True, db_column="phm_affiliation_2_name", null=True
            ),
        ),
    ]
