# Generated by Django 5.0.6 on 2024-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0014_alter_pharmacy_affiliation_2_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volumegroup",
            name="number",
            field=models.BigIntegerField(db_column="vol_number"),
        ),
    ]
