# Generated by Django 5.0.6 on 2024-08-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0015_alter_volumegroup_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="volumegroup",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_column="gsi_group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volumegroup_group_group_id",
                to="pharmacy.group",
            ),
        ),
    ]
