# Generated by Django 5.0.6 on 2024-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0016_volumegroup_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacysalesinfo",
            name="reporting_period_end",
            field=models.DateField(
                blank=True, db_column="psi_reporting_period_end", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacysalesinfo",
            name="reporting_period_start",
            field=models.DateField(
                blank=True, db_column="psi_reporting_period_start", null=True
            ),
        ),
        migrations.AddField(
            model_name="volumegroupsalesinfo",
            name="reporting_period_end",
            field=models.DateField(
                blank=True, db_column="vgi_reporting_period_end", null=True
            ),
        ),
        migrations.AddField(
            model_name="volumegroupsalesinfo",
            name="reporting_period_start",
            field=models.DateField(
                blank=True, db_column="vgi_reporting_period_start", null=True
            ),
        ),
    ]
