# Generated by Django 5.0.6 on 2024-09-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0017_pharmacysalesinfo_reporting_period_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antidiabetic_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antidiabeticglp1_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="antipsychotic_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="brand_rx_dropship_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="brand_rx_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_rx_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_source_overrides",
            field=models.FloatField(
                blank=True, db_column="gsi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="gpo_generic_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="net_generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="net_source_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="non_rx_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="rx_sales",
            field=models.FloatField(blank=True, db_column="gsi_rx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_compliance_pct_base_member",
            field=models.FloatField(
                blank=True, db_column="gsi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_compliance_pct_new_member",
            field=models.FloatField(
                blank=True, db_column="gsi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_override_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="source_sales",
            field=models.FloatField(
                blank=True, db_column="gsi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spd_sales",
            field=models.FloatField(blank=True, db_column="gsi_spd_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_cancer",
            field=models.FloatField(blank=True, db_column="gsi_spx_cancer", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_hep_c",
            field=models.FloatField(blank=True, db_column="gsi_spx_hep_c", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_hiv",
            field=models.FloatField(blank=True, db_column="gsi_spx_hiv", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_ms",
            field=models.FloatField(blank=True, db_column="gsi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_ra",
            field=models.FloatField(blank=True, db_column="gsi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="spx_sales",
            field=models.FloatField(blank=True, db_column="gsi_spx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="groupsalesinfo",
            name="total_sales",
            field=models.FloatField(blank=True, db_column="gsi_total_sales", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="curr_total_volume",
            field=models.FloatField(
                blank=True, db_column="phm_curr_total_volume", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="est_80_committed_amt",
            field=models.FloatField(
                blank=True, db_column="phm_est_80_committed_amt", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="expected_gcr_pct",
            field=models.FloatField(
                blank=True, db_column="phm_expected_gcr_pct", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="hiv_volume",
            field=models.FloatField(blank=True, db_column="phm_hiv_volume", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="affiliation_level3_number",
            field=models.FloatField(
                blank=True, db_column="psi_affiliation_level3_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antidiabetic_sales",
            field=models.FloatField(
                blank=True, db_column="psi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antidiabeticglp1_sales",
            field=models.FloatField(
                blank=True, db_column="psi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="antipsychotic_sales",
            field=models.FloatField(
                blank=True, db_column="psi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="brand_rx_dropship_sales",
            field=models.FloatField(
                blank=True, db_column="psi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="brand_rx_sales",
            field=models.FloatField(
                blank=True, db_column="psi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_rx_sales",
            field=models.FloatField(
                blank=True, db_column="psi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_source_overrides",
            field=models.FloatField(
                blank=True, db_column="psi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="psi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="gpo_generic_sales",
            field=models.FloatField(
                blank=True, db_column="psi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="net_generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="psi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="net_source_sales",
            field=models.FloatField(
                blank=True, db_column="psi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="non_rx_sales",
            field=models.FloatField(
                blank=True, db_column="psi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="rx_sales",
            field=models.FloatField(blank=True, db_column="psi_rx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_compliance_pct_base_member",
            field=models.FloatField(
                blank=True, db_column="psi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_compliance_pct_new_member",
            field=models.FloatField(
                blank=True, db_column="psi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_override_sales",
            field=models.FloatField(
                blank=True, db_column="psi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="source_sales",
            field=models.FloatField(
                blank=True, db_column="psi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spd_sales",
            field=models.FloatField(blank=True, db_column="psi_spd_sales", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_cancer",
            field=models.FloatField(blank=True, db_column="psi_spx_cancer", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_hep_c",
            field=models.FloatField(blank=True, db_column="psi_spx_hep_c", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_hiv",
            field=models.FloatField(blank=True, db_column="psi_spx_hiv", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_ms",
            field=models.FloatField(blank=True, db_column="psi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_ra",
            field=models.FloatField(blank=True, db_column="psi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="spx_sales",
            field=models.FloatField(blank=True, db_column="psi_spx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="total_sales",
            field=models.FloatField(blank=True, db_column="psi_total_sales", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="brand_net",
            field=models.FloatField(blank=True, db_column="rbi_brand_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="brand_rebatable",
            field=models.FloatField(
                blank=True, db_column="rbi_brand_rebatable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="brand_rebate_amt",
            field=models.FloatField(
                blank=True, db_column="rbi_brand_rebate_amt", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="brand_rebate_pct",
            field=models.FloatField(
                blank=True, db_column="rbi_brand_rebate_pct", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="campus_compliance_based_on_net_rx_sales_after_exclusions",
            field=models.FloatField(
                blank=True,
                db_column="rbi_campus_compliance_based_on_net_rx_sales_after_exclusions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="campus_net_rx_after_exclusions",
            field=models.FloatField(
                blank=True, db_column="rbi_campus_net_rx_after_exclusions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="campus_source_sales",
            field=models.FloatField(
                blank=True, db_column="rbi_campus_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="dropship",
            field=models.FloatField(blank=True, db_column="rbi_dropship", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="generic_compliance",
            field=models.FloatField(
                blank=True, db_column="rbi_generic_compliance", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="glp_1_anti_diabetics",
            field=models.FloatField(
                blank=True, db_column="rbi_glp-1_anti-diabetics", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="monthly_source",
            field=models.FloatField(
                blank=True, db_column="rbi_monthly_source", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="monthly_source_rebate_pct_via_campus_compliance",
            field=models.FloatField(
                blank=True,
                db_column="rbi_monthly_source_rebate_pct_via_campus_compliance",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="net_rx_after_exclusions",
            field=models.FloatField(
                blank=True, db_column="rbi_net_rx_after_exclusions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="net_sales",
            field=models.FloatField(blank=True, db_column="rbi_net_sales", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="net_sales_per_location",
            field=models.FloatField(
                blank=True, db_column="rbi_net_sales_per_location", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="payment_terms_rebate_pct",
            field=models.FloatField(
                blank=True, db_column="rbi_payment_terms_rebate_pct", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="payments_terms_rebate_amt",
            field=models.FloatField(
                blank=True, db_column="rbi_payments_terms_rebate_amt", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="revised_payment_terms",
            field=models.FloatField(
                blank=True, db_column="rbi_revised_payment_terms", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="source_rebatable",
            field=models.FloatField(
                blank=True, db_column="rbi_source_rebatable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="source_sales",
            field=models.FloatField(
                blank=True, db_column="rbi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spd_sales",
            field=models.FloatField(blank=True, db_column="rbi_spd_sales", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spx_1_net",
            field=models.FloatField(blank=True, db_column="rbi_spx_1_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spx_2_net",
            field=models.FloatField(blank=True, db_column="rbi_spx_2_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spx_3_net",
            field=models.FloatField(blank=True, db_column="rbi_spx_3_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spx_4_net",
            field=models.FloatField(blank=True, db_column="rbi_spx_4_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="spx_5_net",
            field=models.FloatField(blank=True, db_column="rbi_spx_5_net", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="total_brand",
            field=models.FloatField(blank=True, db_column="rbi_total_brand", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="total_brand_rebate_pct",
            field=models.FloatField(
                blank=True, db_column="rbi_total_brand_rebate_pct", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="total_rx",
            field=models.FloatField(blank=True, db_column="rbi_total_rx", null=True),
        ),
        migrations.AlterField(
            model_name="rebateinfo",
            name="volume_group_compliance_based_on_net_rx_sales_after_exclusions",
            field=models.FloatField(
                blank=True,
                db_column="rbi_volume_group_compliance_based_on_net_rx_sales_after_exclusions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antidiabetic_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_antidiabetic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antidiabeticglp1_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_antidiabeticglp1_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="antipsychotic_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_antipsychotic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="brand_rx_dropship_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_brand_rx_dropship_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="brand_rx_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_brand_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_rx_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_generic_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_source_overrides",
            field=models.FloatField(
                blank=True, db_column="vgi_generic_source_overrides", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="gpo_generic_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_gpo_generic_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="net_generic_source_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_net_generic_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="net_source_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_net_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="non_rx_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_non_rx_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="rx_sales",
            field=models.FloatField(blank=True, db_column="vgi_rx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_compliance_pct_base_member",
            field=models.FloatField(
                blank=True, db_column="vgi_source_compliance_pct_base_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_compliance_pct_new_member",
            field=models.FloatField(
                blank=True, db_column="vgi_source_compliance_pct_new_member", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_override_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_source_override_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="source_sales",
            field=models.FloatField(
                blank=True, db_column="vgi_source_sales", null=True
            ),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spd_sales",
            field=models.FloatField(blank=True, db_column="vgi_spd_sales", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_cancer",
            field=models.FloatField(blank=True, db_column="vgi_spx_cancer", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_hep_c",
            field=models.FloatField(blank=True, db_column="vgi_spx_hep_c", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_hiv",
            field=models.FloatField(blank=True, db_column="vgi_spx_hiv", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_ms",
            field=models.FloatField(blank=True, db_column="vgi_spx_ms", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_ra",
            field=models.FloatField(blank=True, db_column="vgi_spx_ra", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="spx_sales",
            field=models.FloatField(blank=True, db_column="vgi_spx_sales", null=True),
        ),
        migrations.AlterField(
            model_name="volumegroupsalesinfo",
            name="total_sales",
            field=models.FloatField(blank=True, db_column="vgi_total_sales", null=True),
        ),
    ]
