# Generated by Django 5.0.6 on 2024-09-11 09:48

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

status = [
    {"code": "scs", "description": "Succeeded"},
    {"code": "inp", "description": "In-Progress"},
    {"code": "fail", "description": "Failure"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "pharmacy", "ProcessingStatus", status)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "pharmacy", "ProcessingStatus", status)


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0019_processingstatus_fileprocessinglogs"),
    ]

    operations = [
        migrations.RunPython(migrate_core_data, reverse_migrated_core_data),
    ]
