# Generated by Django 5.0.6 on 2024-09-17 13:11

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data


pharmacy_status = [
    {"description": "Completed", "code": "compl"},
    {"description": "In Progress", "code": "inpro"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "pharmacy", "PharmacyStatus", pharmacy_status)


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0020_auto_20240911_1518"),
    ]

    operations = [
        migrations.RunPython(migrate_core_data),
    ]
