# Generated by Django 5.0.6 on 2024-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0021_auto_20240917_1841"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileprocessinglogs",
            name="log",
            field=models.TextField(blank=True, db_column="tat_log", null=True),
        ),
    ]
