# Generated by Django 5.0.6 on 2024-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0022_fileprocessinglogs_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacysalesinfo",
            name="affiliation_level3_name",
            field=models.CharField(
                blank=True,
                db_column="psi_affiliation_level3_name",
                max_length=128,
                null=True,
            ),
        ),
    ]
