# Generated by Django 5.0.6 on 2024-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0023_alter_pharmacysalesinfo_affiliation_level3_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rebateinfo",
            name="monthly_source_admin_fee_amt",
            field=models.FloatField(
                blank=True, db_column="rbi_monthly_source_admin_fee_amt", null=True
            ),
        ),
        migrations.AddField(
            model_name="rebateinfo",
            name="monthly_source_admin_fee_pct",
            field=models.FloatField(
                blank=True, db_column="rbi_monthly_source_admin_fee_pct", null=True
            ),
        ),
    ]
