# Generated by Django 5.0.6 on 2024-10-28 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0024_rebateinfo_monthly_source_admin_fee_amt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacySoftware",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "CFG_PHS_PHARMACYSOFTWARE",
            },
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_column="phm_pharmacy_software",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_software",
                to="pharmacy.pharmacysoftware",
            ),
        ),
    ]
