# Generated by Django 5.0.6 on 2024-10-28 10:12

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

software = [
    {"code": "PR", "description": "PrimeRx"},
    {"code": "LB", "description": "Liberty"},
    {"code": "BR", "description": "BestRx"},
    {"code": "PN", "description": "Pioneer"},
    {"code": "RX", "description": "RX30"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "pharmacy", "PharmacySoftware", software)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "pharmacy", "PharmacySoftware", software)


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0025_pharmacysoftware_pharmacy_software"),
    ]

    operations = [
        migrations.RunPython(migrate_core_data, reverse_migrated_core_data),
    ]
