# Generated by Django 5.0.6 on 2024-10-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0026_auto_20241028_1542"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE public."OPT_PHM_Pharmacy" SET phm_pharmacy_software = (select id from "CFG_PHS_PHARMACYSOFTWARE" where code = 'PR');
            """
        ),
    ]
