# Generated by Django 5.0.6 on 2024-10-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0027_auto_20241028_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="software",
            field=models.ForeignKey(
                db_column="phm_pharmacy_software",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_software",
                to="pharmacy.pharmacysoftware",
            ),
        ),
    ]
