# Generated by Django 5.0.6 on 2024-08-20 11:24

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

table_name_data = [
    {
        "Name": "Person",
        "Type__description": "Operational Table",
        "Group__description": "Person",
        "Prefix": "PER",
    },
    {
        "Name": "Address",
        "Type__description": "Operational Table",
        "Group__description": "Person",
        "Prefix": "ADR",
    },
]
table_attributes_data = [
    {
        "table_name__name": "Person",
        "attrib_name": "first_name",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Person",
        "attrib_name": "last_name",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Person",
        "attrib_name": "email",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Person",
        "attrib_name": "phone",
        "data_type__description": "Integer",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "line1",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "line2",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": True,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "line3",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": True,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "city",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": True,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "state",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "zip",
        "data_type__description": "Integer",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": False,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "zip_plus_four",
        "data_type__description": "Integer",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": True,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
    {
        "table_name__name": "Address",
        "attrib_name": "country",
        "data_type__description": "String",
        "constraint": "",
        "desc": "",
        "position": "",
        "is_nullable": True,
        "char_max_length": "",
        "numeric_precision": "",
        "is_identity": "",
        "identity_generation": "",
        "identity_start": "",
        "identity_increment": "",
        "comment": "",
        "default_value": "",
    },
]
table_group = [
    {"description": "Person", "Code": "person"},
]


def transform_this_data(data):
    return [{key.lower(): val for key, val in eac_rec.items()} for eac_rec in data]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "core", "Tablegroup", transform_this_data(table_group))
    migrate_bulk_data(apps, "core", "Tablename", transform_this_data(table_name_data))
    migrate_bulk_data(
        apps, "core", "Tableattribute", transform_this_data(table_attributes_data)
    )


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(
        apps, "core", "Tableattribute", transform_this_data(table_attributes_data)
    )
    reverse_migrated_bulk_data(
        apps, "core", "Tablename", transform_this_data(table_name_data)
    )
    reverse_migrated_bulk_data(
        apps, "core", "Tablegroup", transform_this_data(table_group)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_core_data, reverse_migrated_core_data),
    ]
