# Generated by Django 5.0.6 on 2024-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_auto_20240820_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="cell",
            field=models.CharField(
                blank=True, db_column="per_cell", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                blank=True, db_column="adr_city", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                blank=True, db_column="adr_country", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="line2",
            field=models.CharField(
                blank=True, db_column="adr_line2", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="line3",
            field=models.CharField(
                blank=True, db_column="adr_line3", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_plus_four",
            field=models.IntegerField(
                blank=True, db_column="adr_zip_plus_four", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(
                blank=True, db_column="per_email", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(
                blank=True, db_column="per_first_name", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(
                blank=True, db_column="per_last_name", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True, db_column="per_phone", max_length=128, null=True
            ),
        ),
    ]
