# Generated by Django 5.0.6 on 2024-10-07 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pharmacy", "0023_alter_pharmacysalesinfo_affiliation_level3_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Distributors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "OPT_DTB_Distributors",
            },
        ),
        migrations.CreateModel(
            name="DistributorAuditData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("ndc", models.BigIntegerField(db_column="dad_ndc")),
                ("quantity", models.BigIntegerField(db_column="dad_quantity")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        db_column="dad_distributor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributor_distributor_audit_data",
                        to="audit.distributors",
                    ),
                ),
            ],
            options={
                "db_table": "OPT_DAD_PharmacyAuditData",
            },
        ),
        migrations.CreateModel(
            name="FileDBMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "source_col_name",
                    models.CharField(db_column="fmp_source_col_name", max_length=128),
                ),
                (
                    "dest_col_name",
                    models.CharField(db_column="fmp_dest_col_name", max_length=128),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        db_column="fmp_distributor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributor_file_db_mapping",
                        to="audit.distributors",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        db_column="fmp_pharmacy",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_file_db_mapping",
                        to="pharmacy.pharmacy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OPT_FMP_FileDBMapping",
            },
        ),
        migrations.CreateModel(
            name="PharmacyAuditData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("ndc", models.BigIntegerField(db_column="pad_ndc")),
                ("brand", models.CharField(db_column="pad_brand", max_length=128)),
                ("strength", models.BigIntegerField(db_column="pad_strength")),
                ("unit_size", models.BigIntegerField(db_column="pad_size")),
                ("quantity", models.BigIntegerField(db_column="pad_quantity")),
                ("drug_name", models.BigIntegerField(db_column="pad_drug_name")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        db_column="pad_pharmacy",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_pharmacyaudit",
                        to="pharmacy.pharmacy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OPT_PAD_PharmacyAuditData",
            },
        ),
    ]
