# Generated by Django 5.0.6 on 2024-10-07 11:28

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data


distributors = [
    {"description": "Mckesson", "code": "mck"},
    {"description": "Anda", "code": "anda"},
    {"description": "Integral Rx", "code": "intrx"},
    {"description": "Citymed", "code": "citym"},
    {"description": "Astor", "code": "astor"},
    {"description": "Bonita", "code": "bon"},
    {"description": "Top Rx", "code": "toprx"},
    {"description": "Kinray", "code": "kinray"},
    {"description": "Akron Gen", "code": "ag"},
    {"description": "Opzeleura", "code": "opzel"},
    {"description": "Real Value", "code": "rv"},
    {"description": "Journey", "code": "journey"},
    {"description": "JG Pharma", "code": "jgp"},
    {"description": "Mayne Pharma", "code": "mp"},
    {"description": "Masters", "code": "mstrs"},
    {"description": "South Pointe", "code": "sp"},
    {"description": "Pharm Source", "code": "ps"},
    {"description": "Oak Drugs", "code": "od"},
    {"description": "Key Srce", "code": "ks"},
    {"description": "Paragon", "code": "pg"},
    {"description": "Quality Care Products", "code": "qcp"},
    {"description": "Dynasty", "code": "dynas"},
    {"description": "Second Source", "code": "2nd_src"},
    {"description": "Medcare", "code": "mc"},
    {"description": "Jams Rx", "code": "jams"},
    {"description": "Wasatch", "code": "was"},
    {"description": "Drug Zone", "code": "dz"},
    {"description": "Allegis", "code": "allegis"},
    {"description": "IPC Rx", "code": "ir"},
    {"description": "Rx Supply", "code": "rs"},
    {"description": "Matrix", "code": "mtrx"},
    {"description": "Nas Rx", "code": "nr"},
    {"description": "Pay less", "code": "pless"},
    {"description": "Global", "code": "glb"},
    {"description": "Primed", "code": "pri"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "audit", "Distributors", distributors)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [migrations.RunPython(migrate_core_data)]
