# Generated by Django 5.0.6 on 2024-10-08 07:23

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data

file_types = [
    {"description": "Pharmacy", "code": "pmc"},
    {"description": "Distributor", "code": "dtb"},
    {"description": "Compared file", "code": "comp"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "audit", "FileType", file_types)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_filetype_processlog_distributorauditdata_process_log_and_more"),
    ]

    operations = [migrations.RunPython(migrate_core_data)]
