# Generated by Django 5.0.6 on 2024-10-08 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_auto_20241008_1253"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessLogHdr",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_column="plg_name", max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OPT_PLG_ProcessLogHdr",
            },
        ),
        migrations.CreateModel(
            name="ProcessLogDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "file_name",
                    models.CharField(db_column="plg_file_name", max_length=256),
                ),
                (
                    "file_url",
                    models.CharField(db_column="plg_file_url", max_length=512),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="plg_file_type",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributor_distributor_audit_data",
                        to="audit.filetype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_log",
                    models.ForeignKey(
                        blank=True,
                        db_column="dad_process_log_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_log_detail_process_log",
                        to="audit.processloghdr",
                    ),
                ),
            ],
            options={
                "db_table": "OPT_PLG_ProcessLogDetail",
            },
        ),
        migrations.AlterField(
            model_name="distributorauditdata",
            name="process_log",
            field=models.ForeignKey(
                blank=True,
                db_column="dad_process_log_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distributor_process_log",
                to="audit.processloghdr",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="process_log",
            field=models.ForeignKey(
                blank=True,
                db_column="pad_process_log_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_process_log",
                to="audit.processloghdr",
            ),
        ),
        migrations.DeleteModel(
            name="ProcessLog",
        ),
    ]
