# Generated by Django 5.0.6 on 2024-10-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_processloghdr_processlogdetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedbmapping",
            name="file_type",
            field=models.ForeignKey(
                blank=True,
                db_column="fmp_file_type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_db_mapping_file_type",
                to="audit.filetype",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="drug_name",
            field=models.CharField(db_column="pad_drug_name", max_length=128),
        ),
        migrations.AlterField(
            model_name="processlogdetail",
            name="file_type",
            field=models.ForeignKey(
                blank=True,
                db_column="plg_file_type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_log_file_type",
                to="audit.filetype",
            ),
        ),
    ]
