# Generated by Django 5.0.6 on 2024-10-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_filedbmapping_file_type_and_more"),
        ("pharmacy", "0023_alter_pharmacysalesinfo_affiliation_level3_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="processlogdetail",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                db_column="dad_distributor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_log_detail_distributor",
                to="audit.distributors",
            ),
        ),
        migrations.AddField(
            model_name="processlogdetail",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                db_column="dad_pharmacy",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_log_detail_pharmacy",
                to="pharmacy.pharmacy",
            ),
        ),
    ]
