# Generated by Django 5.0.6 on 2024-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0007_processlogdetail_distributor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributorauditdata",
            name="quantity",
            field=models.FloatField(db_column="dad_quantity"),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="quantity",
            field=models.FloatField(db_column="pad_quantity"),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="strength",
            field=models.CharField(db_column="pad_strength", max_length=128),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="unit_size",
            field=models.FloatField(db_column="pad_size"),
        ),
    ]
