# Generated by Django 5.0.6 on 2024-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_distributorauditdata_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributorauditdata",
            name="ndc",
            field=models.CharField(db_column="dad_ndc", max_length=40),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="ndc",
            field=models.CharField(db_column="pad_ndc", max_length=40),
        ),
    ]
