# Generated by Django 5.0.6 on 2024-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0009_alter_distributorauditdata_ndc_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="distributorauditdata",
            table="OPT_DAD_DistributorAuditData",
        ),
    ]
