# Generated by Django 5.0.6 on 2024-10-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0010_alter_distributorauditdata_table"),
        ("pharmacy", "0024_rebateinfo_monthly_source_admin_fee_amt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="log",
            field=models.TextField(blank=True, db_column="plg_log", null=True),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="output_file",
            field=models.CharField(
                blank=True, db_column="plg_output_file", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_column="plg_status",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pharmacy.processingstatus",
            ),
        ),
    ]
