# Generated by Django 5.0.6 on 2024-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0011_processloghdr_log_processloghdr_output_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="unit_size",
            field=models.CharField(db_column="pad_size"),
        ),
    ]
