# Generated by Django 5.0.6 on 2024-10-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0012_alter_pharmacyauditdata_unit_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="brand",
            field=models.CharField(
                blank=True, db_column="pad_brand", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="drug_name",
            field=models.CharField(
                blank=True, db_column="pad_drug_name", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="strength",
            field=models.CharField(
                blank=True, db_column="pad_strength", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyauditdata",
            name="unit_size",
            field=models.CharField(
                blank=True, db_column="pad_size", max_length=128, null=True
            ),
        ),
    ]
