# Generated by Django 5.0.6 on 2024-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0013_alter_pharmacyauditdata_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="claim_status",
            field=models.CharField(
                blank=True, db_column="plg_claim_status", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="distributor_from_date",
            field=models.DateField(
                blank=True, db_column="plg_distributor_from_date", null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="distributor_to_date",
            field=models.DateField(
                blank=True, db_column="plg_distributor_to_date", null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="payment_method",
            field=models.CharField(
                blank=True, db_column="plg_payment_method", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="pharmacy_from_date",
            field=models.DateField(
                blank=True, db_column="plg_pharmacy_from_date", null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="pharmacy_to_date",
            field=models.DateField(
                blank=True, db_column="plg_pharmacy_to_date", null=True
            ),
        ),
    ]
