# Generated by Django 5.0.6 on 2024-10-28 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0014_processloghdr_claim_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "CFG_CMS_CLAIMSTATUS",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "CFG_PYM_PAYMENTMETHOD",
            },
        ),
        migrations.RemoveField(
            model_name="processloghdr",
            name="claim_status",
        ),
        migrations.RemoveField(
            model_name="processloghdr",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="claim_status",
            field=models.ManyToManyField(
                blank=True,
                db_column="plg_claim_status",
                null=True,
                related_name="+",
                to="audit.claimstatus",
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="payment_method",
            field=models.ManyToManyField(
                blank=True,
                db_column="plg_payment_method",
                null=True,
                related_name="+",
                to="audit.paymentmethod",
            ),
        ),
    ]
