# Generated by Django 5.0.6 on 2024-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0015_auto_20241030_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="ins_bin_number",
            field=models.FloatField(
                blank=True, db_column="pad_ins_bin_number", null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="ins_paid",
            field=models.FloatField(blank=True, db_column="pad_ins_paid", null=True),
        ),
    ]
