# Generated by Django 5.0.6 on 2024-10-28 11:42

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

methods = [
    {"code": "CA", "description": "Cash"},
    {"code": "IN", "description": "Insurance"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "audit", "PaymentMethod", methods)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "audit", "PaymentMethod", methods)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0015_claimstatus_paymentmethod_and_more"),
    ]

    operations = [migrations.RunPython(migrate_core_data, reverse_migrated_core_data)]
