# Generated by Django 5.0.6 on 2024-10-28 11:46

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

status = [
    {"code": "B", "description": "Billed"},
    {"code": "U", "description": "Unbilled"},
    {"code": "T", "description": "Transferred"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "audit", "ClaimStatus", status)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "audit", "ClaimStatus", status)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0016_auto_20241028_1712"),
    ]

    operations = [migrations.RunPython(migrate_core_data, reverse_migrated_core_data)]
