# Generated by Django 5.0.6 on 2024-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0017_auto_20241028_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processloghdr",
            name="claim_status",
            field=models.ManyToManyField(
                db_column="plg_claim_status", related_name="+", to="audit.claimstatus"
            ),
        ),
        migrations.AlterField(
            model_name="processloghdr",
            name="payment_method",
            field=models.ManyToManyField(
                db_column="plg_payment_method",
                related_name="+",
                to="audit.paymentmethod",
            ),
        ),
    ]
