# Generated by Django 5.0.6 on 2024-10-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0018_alter_processloghdr_claim_status_and_more"),
        ("pharmacy", "0028_alter_pharmacy_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedbmapping",
            name="pharmacy_software",
            field=models.ForeignKey(
                blank=True,
                db_column="fmp_pharmacy_software",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_db_mapping_pharmacy_software",
                to="pharmacy.pharmacysoftware",
            ),
        ),
    ]
