# Generated by Django 5.0.6 on 2024-10-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0016_pharmacyauditdata_ins_bin_number_and_more"),
        ("audit", "0019_filedbmapping_pharmacy_software"),
    ]

    operations = []
