# Generated by Django 5.0.6 on 2024-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0020_merge_20241030_1742"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="patient_copay",
            field=models.FloatField(
                blank=True, db_column="pad_patient_copay", null=True
            ),
        ),
    ]
