# Generated by Django 5.0.6 on 2024-11-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0021_pharmacyauditdata_patient_copay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bingroups",
            name="name",
            field=models.CharField(db_column="bgp_name", max_length=128),
        ),
        migrations.AlterField(
            model_name="binnumbers",
            name="bin_groups",
            field=models.ForeignKey(
                blank=True,
                db_column="bnm_bingroups",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="binnumber_bingroup",
                to="audit.bingroups",
            ),
        ),
        migrations.AlterField(
            model_name="binnumbers",
            name="number",
            field=models.BigIntegerField(blank=True, db_column="bnm_number", null=True),
        ),
    ]
