# Generated by Django 5.0.6 on 2024-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0022_alter_bingroups_name_alter_binnumbers_bin_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorauditdata",
            name="date",
            field=models.DateField(blank=True, db_column="dad_date", null=True),
        ),
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="date",
            field=models.DateField(blank=True, db_column="pad_date", null=True),
        ),
    ]
