# Generated by Django 5.0.6 on 2024-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0023_distributorauditdata_date_pharmacyauditdata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="claim_status",
            field=models.CharField(
                blank=True, db_column="pad_claim_status", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="payment_method",
            field=models.CharField(
                blank=True, db_column="pad_payment_method", max_length=128, null=True
            ),
        ),
    ]
