# Generated by Django 5.0.6 on 2024-11-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0024_pharmacyauditdata_claim_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacyauditdata",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="payment_option",
            field=models.CharField(
                blank=True, db_column="pad_payment_option", max_length=128, null=True
            ),
        ),
    ]
