# Generated by Django 5.0.6 on 2024-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0025_remove_pharmacyauditdata_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="group",
            field=models.CharField(
                blank=True, db_column="pad_group", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pharmacyauditdata",
            name="pcn",
            field=models.CharField(
                blank=True, db_column="pad_pcn", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="group",
            field=models.CharField(
                blank=True, db_column="plg_group", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="pcn",
            field=models.CharField(
                blank=True, db_column="plg_pcn", max_length=128, null=True
            ),
        ),
    ]
