# Generated by Django 5.0.6 on 2024-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0026_pharmacyauditdata_group_pharmacyauditdata_pcn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="bin_number",
            field=models.CharField(
                blank=True, db_column="plg_bin_number", max_length=128, null=True
            ),
        ),
    ]
