# Generated by Django 5.0.6 on 2024-12-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0027_processloghdr_bin_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorauditdata",
            name="drug_name",
            field=models.CharField(
                blank=True, db_column="dad_drug_name", max_length=128, null=True
            ),
        ),
    ]
