# Generated by Django 5.0.6 on 2024-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0028_distributorauditdata_drug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processloghdr",
            name="claim_status",
            field=models.ManyToManyField(
                blank=True,
                db_column="plg_claim_status",
                related_name="+",
                to="audit.claimstatus",
            ),
        ),
        migrations.AlterField(
            model_name="processloghdr",
            name="payment_method",
            field=models.ManyToManyField(
                blank=True,
                db_column="plg_payment_method",
                related_name="+",
                to="audit.paymentmethod",
            ),
        ),
    ]
