# Generated by Django 5.0.6 on 2024-12-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0029_alter_processloghdr_claim_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedbmapping",
            name="date_type",
            field=models.CharField(blank=True, db_column="fmp_date_type", null=True),
        ),
    ]
