# Generated by Django 5.0.6 on 2024-12-06 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0030_filedbmapping_date_type"),
        ("pharmacy", "0028_alter_pharmacy_software"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanFilesLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(db_column="cfl_name", max_length=128)),
                (
                    "input_file_name",
                    models.CharField(
                        blank=True,
                        db_column="cfl_input_file_name",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "input_file_url",
                    models.CharField(
                        blank=True,
                        db_column="cfl_input_file_url",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "output_file_url",
                    models.CharField(
                        blank=True,
                        db_column="cfl_output_file_url",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_column="cfl_status",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.processingstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "OPT_CFL_CleanFilesLog",
            },
        ),
    ]
