# Generated by Django 5.0.6 on 2024-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0031_cleanfileslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleanfileslog",
            name="log",
            field=models.TextField(blank=True, db_column="plg_log", null=True),
        ),
    ]
