# Generated by Django 5.0.6 on 2024-12-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0032_cleanfileslog_log"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PSI_PharmacySalesInfo"
            WHERE psi_pharmacy IN (
                '4b04f492-d176-461c-b264-27fda719d007',
                '5da2be7a-23dc-46d4-a3d0-eef0ffbd173f',
                '5f943295-111e-42cc-948b-7db7a6357d3f',
                '677e152b-d05d-458c-8a3b-83a0881efe81',
                '87535f68-1550-4983-a453-10478fadb3ef',
                '8974b80b-fc06-4467-bcec-d8d68bd44d4c',
                '9043805f-be66-4b28-9b1a-e1334ea95b00',
                '91592af7-3e6b-438d-8331-f4384bd9a270',
                '97bd7755-7fe8-4a70-a5f3-a76c61e2d015',
                '9dc7f134-08ce-48e3-8bb7-52f773352510',
                'a6ffe3cf-af31-4bb9-b3ba-5ac5316eb288',
                'afc8c26a-7310-423d-bc27-f954f3c04290',
                'b2d6539f-0681-4d47-bc8a-fd5d687a62c0',
                'bdde5cd7-ef37-4911-9ee8-e898d3b0965d',
                'c0380995-254a-402a-bfec-b7e1c5560d59',
                'deefbda9-1839-4fd0-b39d-a8044ec6296d',
                'f41df207-5e68-40fe-a1b7-3a289a8a3655',
                'f529af3b-7402-48bd-b3ef-bc481f0ed954',
                'fe3a59b7-6713-4f8c-816e-eb4a9ffbeda9',
                '18809a5c-f5ee-41f7-a2ee-02f37428ba64',
                '45964546-1ae0-4615-93c3-5078cece8d5b'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_RBI_RebateInfo"
            WHERE rbi_pharmacy IN (
                '4b04f492-d176-461c-b264-27fda719d007',
                '5da2be7a-23dc-46d4-a3d0-eef0ffbd173f',
                '5f943295-111e-42cc-948b-7db7a6357d3f',
                '677e152b-d05d-458c-8a3b-83a0881efe81',
                '87535f68-1550-4983-a453-10478fadb3ef',
                '8974b80b-fc06-4467-bcec-d8d68bd44d4c',
                '9043805f-be66-4b28-9b1a-e1334ea95b00',
                '91592af7-3e6b-438d-8331-f4384bd9a270',
                '97bd7755-7fe8-4a70-a5f3-a76c61e2d015',
                '9dc7f134-08ce-48e3-8bb7-52f773352510',
                'a6ffe3cf-af31-4bb9-b3ba-5ac5316eb288',
                'afc8c26a-7310-423d-bc27-f954f3c04290',
                'b2d6539f-0681-4d47-bc8a-fd5d687a62c0',
                'bdde5cd7-ef37-4911-9ee8-e898d3b0965d',
                'c0380995-254a-402a-bfec-b7e1c5560d59',
                'deefbda9-1839-4fd0-b39d-a8044ec6296d',
                'f41df207-5e68-40fe-a1b7-3a289a8a3655',
                'f529af3b-7402-48bd-b3ef-bc481f0ed954',
                'fe3a59b7-6713-4f8c-816e-eb4a9ffbeda9',
                '18809a5c-f5ee-41f7-a2ee-02f37428ba64',
                '45964546-1ae0-4615-93c3-5078cece8d5b'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PHM_Pharmacy"
            WHERE id IN (
                '4b04f492-d176-461c-b264-27fda719d007',
                '5da2be7a-23dc-46d4-a3d0-eef0ffbd173f',
                '5f943295-111e-42cc-948b-7db7a6357d3f',
                '677e152b-d05d-458c-8a3b-83a0881efe81',
                '87535f68-1550-4983-a453-10478fadb3ef',
                '8974b80b-fc06-4467-bcec-d8d68bd44d4c',
                '9043805f-be66-4b28-9b1a-e1334ea95b00',
                '91592af7-3e6b-438d-8331-f4384bd9a270',
                '97bd7755-7fe8-4a70-a5f3-a76c61e2d015',
                '9dc7f134-08ce-48e3-8bb7-52f773352510',
                'a6ffe3cf-af31-4bb9-b3ba-5ac5316eb288',
                'afc8c26a-7310-423d-bc27-f954f3c04290',
                'b2d6539f-0681-4d47-bc8a-fd5d687a62c0',
                'bdde5cd7-ef37-4911-9ee8-e898d3b0965d',
                'c0380995-254a-402a-bfec-b7e1c5560d59',
                'deefbda9-1839-4fd0-b39d-a8044ec6296d',
                'f41df207-5e68-40fe-a1b7-3a289a8a3655',
                'f529af3b-7402-48bd-b3ef-bc481f0ed954',
                'fe3a59b7-6713-4f8c-816e-eb4a9ffbeda9',
                '18809a5c-f5ee-41f7-a2ee-02f37428ba64',
                '45964546-1ae0-4615-93c3-5078cece8d5b'
            );
            """
        ),
    ]
