# Generated by Django 5.0.6 on 2024-12-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0033_auto_20241210_1835"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PSI_PharmacySalesInfo"
            WHERE psi_pharmacy IN (
                'e4f21f83-5ef8-4be8-8eb3-75660bee3381',
                '92acb38a-fe89-479a-9967-e26151e869aa',
                'e49ebb32-15ea-404a-811e-f83a973914c2',
                '870360c1-2a95-4396-9a87-e3699c8cca8a',
	            '9a44080e-2a86-4dd6-bd73-77c4ce291073'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_RBI_RebateInfo"
            WHERE rbi_pharmacy IN (
                'e4f21f83-5ef8-4be8-8eb3-75660bee3381',
                '92acb38a-fe89-479a-9967-e26151e869aa',
                'e49ebb32-15ea-404a-811e-f83a973914c2',
                '870360c1-2a95-4396-9a87-e3699c8cca8a',
	            '9a44080e-2a86-4dd6-bd73-77c4ce291073'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PLG_ProcessLogDetail"
            WHERE dad_pharmacy IN (
                'e4f21f83-5ef8-4be8-8eb3-75660bee3381',
                '92acb38a-fe89-479a-9967-e26151e869aa',
                'e49ebb32-15ea-404a-811e-f83a973914c2',
                '870360c1-2a95-4396-9a87-e3699c8cca8a',
	            '9a44080e-2a86-4dd6-bd73-77c4ce291073'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PAD_PharmacyAuditData"
            WHERE pad_pharmacy IN (
                'e4f21f83-5ef8-4be8-8eb3-75660bee3381',
                '92acb38a-fe89-479a-9967-e26151e869aa',
                'e49ebb32-15ea-404a-811e-f83a973914c2',
                '870360c1-2a95-4396-9a87-e3699c8cca8a',
	            '9a44080e-2a86-4dd6-bd73-77c4ce291073'
            );
            """
        ),
        migrations.RunSQL(
            """
            DELETE FROM public."OPT_PHM_Pharmacy"
            WHERE id IN (
                'e4f21f83-5ef8-4be8-8eb3-75660bee3381',
                '92acb38a-fe89-479a-9967-e26151e869aa',
                'e49ebb32-15ea-404a-811e-f83a973914c2',
                '870360c1-2a95-4396-9a87-e3699c8cca8a',
	            '9a44080e-2a86-4dd6-bd73-77c4ce291073'
            );
            """
        ),
    ]
