# Generated by Django 5.0.6 on 2025-01-02 11:05

from django.db import migrations
from core.migrations.utilities.util import migrate_bulk_data, reverse_migrated_bulk_data

types = [
    {"code": "ER", "description": "Error"},
    {"code": "IN", "description": "Info"},
    {"code": "WA", "description": "Warning"},
    {"code": "CR", "description": "Critical"},
]


def migrate_core_data(apps, schema_editor):
    migrate_bulk_data(apps, "audit", "ErrorSeverity", types)


def reverse_migrated_core_data(apps, schema_editor):
    reverse_migrated_bulk_data(apps, "audit", "ErrorSeverity", types)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0035_errorseverity_errorlogs"),
    ]

    operations = [migrations.RunPython(migrate_core_data, reverse_migrated_core_data)]
