# Generated by Django 5.0.6 on 2025-02-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0036_auto_20250102_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributorauditdata",
            name="drug_name",
            field=models.CharField(
                blank=True, db_column="dad_drug_name", max_length=512, null=True
            ),
        ),
    ]
