# Generated by Django 5.1.3 on 2025-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0036_auto_20250102_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="failed_count",
            field=models.IntegerField(
                blank=True, db_column="plg_failed_count", null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="processed_count",
            field=models.IntegerField(
                blank=True, db_column="plg_processed_count", null=True
            ),
        ),
    ]
