# Generated by Django 5.0.6 on 2025-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0037_alter_distributorauditdata_drug_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="files_processed",
            field=models.IntegerField(
                blank=True, db_column="plg_files_processed", default=0, null=True
            ),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="total_files",
            field=models.IntegerField(
                blank=True, db_column="plg_total_files", default=0, null=True
            ),
        ),
    ]
