# Generated by Django 5.1.3 on 2025-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0037_processloghdr_failed_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="failed_files_json",
            field=models.JSONField(blank=True, db_column="plg_failed_files", null=True),
        ),
    ]
