# Generated by Django 5.1.3 on 2025-10-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0038_processloghdr_failed_files_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="processloghdr",
            name="distributor_failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="distributor_processed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="pharmacy_failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processloghdr",
            name="pharmacy_processed_count",
            field=models.IntegerField(default=0),
        ),
    ]
