# Generated by Django 5.1.3 on 2025-10-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0039_processloghdr_distributor_failed_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processloghdr",
            name="distributor_failed_count",
            field=models.IntegerField(
                blank=True,
                db_column="plg_distributor_failed_count",
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processloghdr",
            name="distributor_processed_count",
            field=models.IntegerField(
                blank=True,
                db_column="plg_distributor_processed_count",
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processloghdr",
            name="pharmacy_failed_count",
            field=models.IntegerField(
                blank=True, db_column="plg_pharmacy_failed_count", default=0, null=True
            ),
        ),
        migrations.AlterField(
            model_name="processloghdr",
            name="pharmacy_processed_count",
            field=models.IntegerField(
                blank=True,
                db_column="plg_pharmacy_processed_count",
                default=0,
                null=True,
            ),
        ),
    ]
