# Generated by Django 5.1.3 on 2025-10-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0040_alter_processloghdr_distributor_failed_count_and_more"),
        ("pharmacy", "0028_alter_pharmacy_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedbmapping",
            name="volume_group",
            field=models.ForeignKey(
                blank=True,
                db_column="fmp_volume_group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="volume_group_file_db_mapping",
                to="pharmacy.volumegroup",
            ),
        ),
        migrations.AlterField(
            model_name="filedbmapping",
            name="date_type",
            field=models.CharField(
                blank=True, db_column="fmp_date_type", max_length=128, null=True
            ),
        ),
    ]
