# Generated by Django 5.0.6 on 2024-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="template_path",
        ),
        migrations.AddField(
            model_name="template",
            name="template_file",
            field=models.TextField(
                blank=True, db_column="tpl_template_file", null=True
            ),
        ),
    ]
