# Generated by Django 5.0.6 on 2024-08-28 10:08

from django.db import migrations

template_column_mapping = {
    "Buying_Group": "volume_group__name",
    "Checkbox_1": "is_kinray_lead",
    "Checkbox_2": "is_cardinal_lead",
    "Date": "created_at__date",
    "Pharmacy_Name": "corp_name",
    "DBA": "dba",
    "Address": "address__line1",
    "City-State-Zip": "address__city_state_zip",
    "Phone": "phone",
    "Fax": "fax",
    "Email": "email",
    "Cell": "cell",
    "Contact_Name": "contact_name",
    "Principal_Owner": "principal_name",
    "Primary_Wholesaler": "curr_primary_wholesaler",
    "Total_Volume": "curr_total_volume",
    "Committed_Amount": "est_80_committed_amt",
    "HIV": "hiv_volume",
    "GCR": "expected_gcr_pct",
    "Checkbox_3": "is_affiliated_member",
    "Checkbox_4": "is_un_affiliated_member",
    "Checkbox_5": "is_startup_pharma",
    "Checkbox_6": "is_sub_group_member",
    "Sub_Group": "sub_group_name",
    "Payment": "proposed_payment_terms",
}


def insert_template_obj(apps, schema_editor):
    template = apps.get_model(app_label="correspondence", model_name="Template")
    new_pharma_template = template.objects.create(
        template_form="add_new_pharmacy", template_file="allwin_lead.pdf"
    )
    template_detail = apps.get_model(
        app_label="correspondence", model_name="TemplateDetails"
    )
    detail_objs = []
    for key, val in template_column_mapping.items():
        detail_objs.append(
            template_detail(
                app_name="Pharmacy",
                table_name="Pharmacy",
                col_name=val,
                template_fieldname=key,
                template=new_pharma_template,
            )
        )
    template_detail.objects.bulk_create(detail_objs)


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0002_remove_template_template_path_template_template_file"),
    ]

    operations = [
        migrations.RunPython(insert_template_obj),
    ]
